### ISSUE TITLE
Multiselect showing [object object] with selected values

### ISSUE THREAD

**Issue by mckelveygreg** [lukasbach/ink-form#4]
Not sure where the issue is, but your examples work great and my code works in this repo, but the code from npm produces `[object object]` in the ui for whatever is selected. 

DevTools shows the same values in the example vs my code. I found that installing what is in github directly with yalc fixes the issue. Perhaps some changes didn't get deployed to npm in the 1.0.1 version?

**Comment by tajo48** [comment]
Same problem pls send help

**Comment by merrywhether** [comment]
This was fixed with the [addition of the `.map(...)` in this commit](https://github.com/lukasbach/ink-form/commit/c984d774a2fba3413f89aee88f7d8a476b9bdb06#diff-144acdbb974187ceb92c7d83d9dc54f6e369eae3b9c7afd28c722e32d85f8d33R26), but the map is not in the published code:
```
_b = (_a = props.field.options.filter(function (option) { var _a; return (_a = props.value) === null || _a === void 0 ? void 0 : _a.includes(option.value); })) === null || _a === void 0 ? void 0 : _a.join(', ')
```

Looking at the rest of the build output, it looks like the 1.0.1 publish was against a stale `lib` directory because a lot of other old files are in there too (like `FormFieldMultiSelectRenderer`). A new publish from latest main should easily fix this.

In the meantime, if you use `patch-package` you can just apply the newly built version of `this.renderValue` in `lib/managers/MultiSelectFormFieldManager.js`:
```js
        this.renderValue = function (props) {
            var _a, _b, _c;
            return (react_1.default.createElement(react_1.default.Fragment, null, (_c = (_b = (_a = props.field.options
                .filter(function (option) { var _a; return (_a = props.value) === null || _a === void 0 ? void 0 : _a.includes(option.value); })) === null || _a === void 0 ? void 0 : _a.map(function (option) { var _a; return (_a = option.label) !== null && _a !== void 0 ? _a : option.value; })) === null || _b === void 0 ? void 0 : _b.join(', ')) !== null && _c !== void 0 ? _c : 'No value'));
        };
```

**Comment by lukasbach** [comment]
Hi, sorry for the late answer. I republished the package with the latest code, please let me know if issues persist.
